feign:
  client:
    url:
      mirrorserviceurl: http://mirrorservice:8080
      simpleserviceurl: http://simpleservice:8201
      sharedjobserviceurl: http://sharedjobservice:8008
  hystrix:
    enabled: false
