spring:
    cloud:
        stream:
            bindings:
                output:
                    content-type: application/json
                    destination: HazelcastWorkDto
                    group: HazelcastWork
                    producer:
                        sync: true
            kafka:
                binder:
                    autoCreateTopics: true
                    brokers: nuc:9092
                    replicationFactor: 1
                    requiredAcks: 1
