spring:
    data:
        mongodb:
            authentication-database: admin
            database: spring
            host: nuc
            password: spring
            port: 27017
            repositories:
                type: auto
            username: spring
