spring:
    datasource:
        username: audit
        password: audit
        url: jdbc:postgresql://nuc:5432/audit
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
                show_sql: false
                use_sql_comments: false
