spring:
    batch:
        initialize-schema: always
    datasource:
        username: spring
        password: spring
        url: jdbc:postgresql://nuc:5432/spring
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
                show_sql: false
                use_sql_comments: false
