spring:
    cloud:
        stream:
            bindings:
                input:
                    content-type: application/json
                    group: tasksWorker
                    destination: queue.tasks
                    binder: rabbit_server
            binders:
               rabbit_server:
                  type: rabbit
                  environment:
                     spring:
                        rabbitmq:
                           host: nuc
                           port: 5672
                           username: spring
                           password: spring
                           virtual-host: /spring
                           use-ssl: false
    jpa:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
datasource:
    tasklog:
        driver-class-name: org.mariadb.jdbc.Driver
        password: tasklog
        url: jdbc:mariadb://nuc:3306/tasklog
        username: tasklog
