spring:
    cloud:
        stream:
            bindings:
                output:
                    content-type: application/json
                    destination: queue.tasks
                    binder: rabbit_server
            binders:
               rabbit_server:
                  type: rabbit
                  environment:
                     spring:
                        rabbitmq:
                           host: nuc
                           port: 5672
                           username: guest
                           password: guest
                           virtual-host: /
    jpa:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
datasource:
    tasklog:
        driver-class-name: org.mariadb.jdbc.Driver
        password: tasklog
        url: jdbc:mariadb://nuc:3306/tasklog
        username: tasklog
