spring:
    cloud:
        stream:
            bindings:
                output:
                    content-type: application/json
                    destination: queue.tasks
                    binder: rabbit_server
            binders:
               rabbit_server:
                  type: rabbit
                  environment:
                     spring:
                        rabbitmq:
                           host: nuc
                           port: 5672
                           username: spring
                           password: spring
                           virtual-host: /spring
                           use-ssl: false
                           
