spring:
    cloud:
        stream:
            bindings:
                input:
                    content-type: application/json
                    group: tasksWorker
                    destination: queue.tasks
                    binder: rabbit_server
            binders:
               rabbit_server:
                  type: rabbit
                  environment:
                     spring:
                        rabbitmq:
                           host: nuc
                           port: 5672
                           username: guest
                           password: guest
                           virtual-host: /
